### PR TITLE
Fix s3 pagination

### PR DESCRIPTION
**Pull request by chrislusf**
# What problem are we solving?

there are regression on s3 listing objects
https://github.com/seaweedfs/seaweedfs/issues/3166

# How are we solving the problem?

1. Revert most code to original format.
2. Use cursor to visit directory tree
3. Add back empty folder handling.

# How is the PR tested?

Tested with different cases
```
aws --endpoint-url http://127.0.0.1:8333/ s3api list-objects-v2 --bucket test --prefix 'parent' --page-size 6 --starting-token parentDir/data/04/048f9fcb25c17885cfc0

aws --endpoint-url http://127.0.0.1:8333/ s3api list-objects-v2 --bucket test --prefix '/parentDir/data/' --page-size 6 --starting-token parentDir/data/04/04e4573a4e2bfb5067ac

aws --endpoint-url http://127.0.0.1:8333/ s3api list-objects-v2 --bucket test --prefix '/parentDir/data/0' --page-size 6 --starting-token parentDir/data/04/04e4573a4e2bfb5067ac

aws --endpoint-url http://127.0.0.1:8333/ s3api list-objects-v2 --bucket test --prefix '' --page-size 6 --starting-token parentDir/data/04/048f9fcb25c17885cfc0
```

# Checks
- [ ] I have added unit tests if possible.
- [ ] I will add related wiki document changes and link to this PR after merging.

### CODE REVIEW

**Comment by chrislusf** [comment]
still these tests are failing

```

s3tests_1  | ======================================================================
s3tests_1  | FAIL: s3tests_boto3.functional.test_s3.test_bucket_list_many
s3tests_1  | ----------------------------------------------------------------------
s3tests_1  | Traceback (most recent call last):
s3tests_1  |   File "/opt/s3-tests/virtualenv/lib/python3.8/site-packages/nose/case.py", line 198, in runTest
s3tests_1  |     self.test(*self.arg)
s3tests_1  |   File "/opt/s3-tests/s3tests_boto3/functional/test_s3.py", line 165, in test_bucket_list_many
s3tests_1  |     eq(response['IsTruncated'], True)
s3tests_1  | AssertionError: False != True
s3tests_1  | >>  raise AssertionError(None or "%r != %r" % (False, True))
s3tests_1  |
s3tests_1  |
s3tests_1  | ======================================================================
s3tests_1  | FAIL: s3tests_boto3.functional.test_s3.test_bucket_listv2_many
s3tests_1  | ----------------------------------------------------------------------
s3tests_1  | Traceback (most recent call last):
s3tests_1  |   File "/opt/s3-tests/virtualenv/lib/python3.8/site-packages/nose/case.py", line 198, in runTest
s3tests_1  |     self.test(*self.arg)
s3tests_1  |   File "/opt/s3-tests/s3tests_boto3/functional/test_s3.py", line 187, in test_bucket_listv2_many
s3tests_1  |     eq(response['IsTruncated'], True)
s3tests_1  | AssertionError: False != True
s3tests_1  | >>  raise AssertionError(None or "%r != %r" % (False, True))
s3tests_1  |
s3tests_1  |
s3tests_1  | ======================================================================
s3tests_1  | FAIL: s3tests_boto3.functional.test_s3.test_bucket_listv2_delimiter_prefix
s3tests_1  | ----------------------------------------------------------------------
s3tests_1  | Traceback (most recent call last):
s3tests_1  |   File "/opt/s3-tests/virtualenv/lib/python3.8/site-packages/nose/case.py", line 198, in runTest
s3tests_1  |     self.test(*self.arg)
s3tests_1  |   File "/opt/s3-tests/s3tests_boto3/functional/test_s3.py", line 374, in test_bucket_listv2_delimiter_prefix
s3tests_1  |     continuation_token = validate_bucket_listv2(bucket_name, prefix, delim, None, 1, True, ['asdf'], [])
s3tests_1  |   File "/opt/s3-tests/s3tests_boto3/functional/test_s3.py", line 318, in validate_bucket_listv2
s3tests_1  |     eq(response['IsTruncated'], is_truncated)
s3tests_1  | AssertionError: False != True
s3tests_1  | >>  raise AssertionError(None or "%r != %r" % (False, True))
s3tests_1  |
s3tests_1  |
s3tests_1  | ======================================================================
s3tests_1  | FAIL: s3tests_boto3.functional.test_s3.test_bucket_listv2_delimiter_prefix_underscore
s3tests_1  | ----------------------------------------------------------------------
s3tests_1  | Traceback (most recent call last):
s3tests_1  |   File "/opt/s3-tests/virtualenv/lib/python3.8/site-packages/nose/case.py", line 198, in runTest
s3tests_1  |     self.test(*self.arg)
s3tests_1  |   File "/opt/s3-tests/s3tests_boto3/functional/test_s3.py", line 486, in test_bucket_listv2_delimiter_prefix_underscore
s3tests_1  |     continuation_token  = validate_bucket_listv2(bucket_name, prefix, delim, None, 1, True, ['_obj1_'], [])
s3tests_1  |   File "/opt/s3-tests/s3tests_boto3/functional/test_s3.py", line 318, in validate_bucket_listv2
s3tests_1  |     eq(response['IsTruncated'], is_truncated)
s3tests_1  | AssertionError: False != True
s3tests_1  | >>  raise AssertionError(None or "%r != %r" % (False, True))
s3tests_1  |
s3tests_1  |
s3tests_1  | ======================================================================
s3tests_1  | FAIL: s3tests_boto3.functional.test_s3.test_bucket_list_prefix_delimiter_basic
s3tests_1  | ----------------------------------------------------------------------
s3tests_1  | Traceback (most recent call last):
s3tests_1  |   File "/opt/s3-tests/virtualenv/lib/python3.8/site-packages/nose/case.py", line 198, in runTest
s3tests_1  |     self.test(*self.arg)
s3tests_1  |   File "/opt/s3-tests/s3tests_boto3/functional/test_s3.py", line 1052, in test_bucket_list_prefix_delimiter_basic
s3tests_1  |     eq(keys, ['foo/bar'])
s3tests_1  | AssertionError: [] != ['foo/bar']
s3tests_1  | >>  raise AssertionError(None or "%r != %r" % ([], ['foo/bar']))
s3tests_1  |
s3tests_1  |
s3tests_1  | ======================================================================
s3tests_1  | FAIL: s3tests_boto3.functional.test_s3.test_bucket_listv2_prefix_delimiter_basic
s3tests_1  | ----------------------------------------------------------------------
s3tests_1  | Traceback (most recent call last):
s3tests_1  |   File "/opt/s3-tests/virtualenv/lib/python3.8/site-packages/nose/case.py", line 198, in runTest
s3tests_1  |     self.test(*self.arg)
s3tests_1  |   File "/opt/s3-tests/s3tests_boto3/functional/test_s3.py", line 1072, in test_bucket_listv2_prefix_delimiter_basic
s3tests_1  |     eq(keys, ['foo/bar'])
s3tests_1  | AssertionError: [] != ['foo/bar']
s3tests_1  | >>  raise AssertionError(None or "%r != %r" % ([], ['foo/bar']))
s3tests_1  |
s3tests_1  |
s3tests_1  | ======================================================================
s3tests_1  | FAIL: s3tests_boto3.functional.test_s3.test_bucket_list_maxkeys_one
s3tests_1  | ----------------------------------------------------------------------
s3tests_1  | Traceback (most recent call last):
s3tests_1  |   File "/opt/s3-tests/virtualenv/lib/python3.8/site-packages/nose/case.py", line 198, in runTest
s3tests_1  |     self.test(*self.arg)
s3tests_1  |   File "/opt/s3-tests/s3tests_boto3/functional/test_s3.py", line 1226, in test_bucket_list_maxkeys_one
s3tests_1  |     eq(response['IsTruncated'], True)
s3tests_1  | AssertionError: False != True
s3tests_1  | >>  raise AssertionError(None or "%r != %r" % (False, True))
s3tests_1  |
s3tests_1  |
s3tests_1  | ======================================================================
s3tests_1  | FAIL: s3tests_boto3.functional.test_s3.test_bucket_listv2_maxkeys_one
s3tests_1  | ----------------------------------------------------------------------
s3tests_1  | Traceback (most recent call last):
s3tests_1  |   File "/opt/s3-tests/virtualenv/lib/python3.8/site-packages/nose/case.py", line 198, in runTest
s3tests_1  |     self.test(*self.arg)
s3tests_1  |   File "/opt/s3-tests/s3tests_boto3/functional/test_s3.py", line 1249, in test_bucket_listv2_maxkeys_one
s3tests_1  |     eq(response['IsTruncated'], True)
s3tests_1  | AssertionError: False != True
s3tests_1  | >>  raise AssertionError(None or "%r != %r" % (False, True))
s3tests_1  |
s3tests_1  |
s3tests_1  | ----------------------------------------------------------------------
s3tests_1  | XML: /opt/s3-tests/nosetests.xml
s3tests_1  | ----------------------------------------------------------------------
s3tests_1  | Ran 146 tests in 54.310s
s3tests_1  |
```

**Comment by chrislusf** [comment]
after IsTruncated fix:


```
s3tests_1  | ======================================================================
s3tests_1  | FAIL: s3tests_boto3.functional.test_s3.test_bucket_listv2_delimiter_prefix
s3tests_1  | ----------------------------------------------------------------------
s3tests_1  | Traceback (most recent call last):
s3tests_1  |   File "/opt/s3-tests/virtualenv/lib/python3.8/site-packages/nose/case.py", line 198, in runTest
s3tests_1  |     self.test(*self.arg)
s3tests_1  |   File "/opt/s3-tests/s3tests_boto3/functional/test_s3.py", line 383, in test_bucket_listv2_delimiter_prefix
s3tests_1  |     continuation_token = validate_bucket_listv2(bucket_name, prefix, delim, None, 1, True, ['boo/bar'], [])
s3tests_1  |   File "/opt/s3-tests/s3tests_boto3/functional/test_s3.py", line 318, in validate_bucket_listv2
s3tests_1  |     eq(response['IsTruncated'], is_truncated)
s3tests_1  | AssertionError: False != True
s3tests_1  | >>  raise AssertionError(None or "%r != %r" % (False, True))
s3tests_1  |
s3tests_1  |
s3tests_1  | ======================================================================
s3tests_1  | FAIL: s3tests_boto3.functional.test_s3.test_bucket_listv2_delimiter_prefix_underscore
s3tests_1  | ----------------------------------------------------------------------
s3tests_1  | Traceback (most recent call last):
s3tests_1  |   File "/opt/s3-tests/virtualenv/lib/python3.8/site-packages/nose/case.py", line 198, in runTest
s3tests_1  |     self.test(*self.arg)
s3tests_1  |   File "/opt/s3-tests/s3tests_boto3/functional/test_s3.py", line 495, in test_bucket_listv2_delimiter_prefix_underscore
s3tests_1  |     continuation_token  = validate_bucket_listv2(bucket_name, prefix, delim, None, 1, True, ['_under1/bar'], [])
s3tests_1  |   File "/opt/s3-tests/s3tests_boto3/functional/test_s3.py", line 318, in validate_bucket_listv2
s3tests_1  |     eq(response['IsTruncated'], is_truncated)
s3tests_1  | AssertionError: False != True
s3tests_1  | >>  raise AssertionError(None or "%r != %r" % (False, True))
s3tests_1  |
s3tests_1  |
s3tests_1  | ======================================================================
s3tests_1  | FAIL: s3tests_boto3.functional.test_s3.test_bucket_list_prefix_delimiter_basic
s3tests_1  | ----------------------------------------------------------------------
s3tests_1  | Traceback (most recent call last):
s3tests_1  |   File "/opt/s3-tests/virtualenv/lib/python3.8/site-packages/nose/case.py", line 198, in runTest
s3tests_1  |     self.test(*self.arg)
s3tests_1  |   File "/opt/s3-tests/s3tests_boto3/functional/test_s3.py", line 1052, in test_bucket_list_prefix_delimiter_basic
s3tests_1  |     eq(keys, ['foo/bar'])
s3tests_1  | AssertionError: [] != ['foo/bar']
s3tests_1  | >>  raise AssertionError(None or "%r != %r" % ([], ['foo/bar']))
s3tests_1  |
s3tests_1  |
s3tests_1  | ======================================================================
s3tests_1  | FAIL: s3tests_boto3.functional.test_s3.test_bucket_listv2_prefix_delimiter_basic
s3tests_1  | ----------------------------------------------------------------------
s3tests_1  | Traceback (most recent call last):
s3tests_1  |   File "/opt/s3-tests/virtualenv/lib/python3.8/site-packages/nose/case.py", line 198, in runTest
s3tests_1  |     self.test(*self.arg)
s3tests_1  |   File "/opt/s3-tests/s3tests_boto3/functional/test_s3.py", line 1072, in test_bucket_listv2_prefix_delimiter_basic
s3tests_1  |     eq(keys, ['foo/bar'])
s3tests_1  | AssertionError: [] != ['foo/bar']
s3tests_1  | >>  raise AssertionError(None or "%r != %r" % ([], ['foo/bar']))
s3tests_1  |
s3tests_1  |
s3tests_1  | ----------------------------------------------------------------------
s3tests_1  | XML: /opt/s3-tests/nosetests.xml
s3tests_1  | ----------------------------------------------------------------------
```

**Comment by chrislusf** [comment]
all tests passed

**Comment by chrislusf** [comment]
@kmlebedev could you please help to test? Especially the https://github.com/seaweedfs/seaweedfs/issues/3086

**Comment by kmlebedev** [comment]
> all tests passed

Cool

**Comment by kmlebedev** [comment]
> @kmlebedev could you please help to test this PR? Especially the #3086

not work
```
aws --endpoint-url http://127.0.0.1:8333 s3api put-object --bucket test --key "fakedir/"
aws --endpoint-url http://127.0.0.1:8333 s3api list-objects-v2 --bucket test --prefix "fakedir/"
{
    "Contents": [
        {
            "Key": "fakedir/",
            "LastModified": "2022-05-25T13:57:23+00:00",
            "ETag": "\"d41d8cd98f00b204e9800998ecf8427e-0\"",
            "Size": 0,
            "StorageClass": "STANDARD",
            "Owner": {
                "ID": "0"
            }
        }
    ]
}
```

Folder not showing
log
```
s3_1         | I0813 12:12:56.889575 filer_grpc_server.go:40 ListEntries directory:"/buckets/test/fakedir"  limit:10001
s3_1         | I0813 12:12:56.890563 filer_grpc_server.go:40 ListEntries directory:"/buckets/test/fakedir2"  limit:10001
s3_1         | I0813 12:12:56.891445 filer_grpc_server.go:40 ListEntries directory:"/buckets/test/lol"  limit:10001
s3_1         | I0813 12:12:56.892360 filer_grpc_server.go:40 ListEntries directory:"/buckets/test/proverka"  limit:10001
s3_1         | I0813 12:12:56.893317 filer_grpc_server.go:40 ListEntries directory:"/buckets/test/test5"  limit:10001
s3_1         | I0813 12:12:56.893935 error_handler.go:85 status 200 application/xml: <?xml version="1.0" encoding="UTF-8"?>

```

**Comment by chrislusf** [comment]
added a fix that can work for this case.

```
aws --endpoint-url http://127.0.0.1:8333/ s3api list-objects-v2 --bucket test --prefix "fakedir"
{
    "Contents": [
        {
            "Key": "fakedir/",
            "LastModified": "2022-08-13T21:40:45+00:00",
            "ETag": "\"d41d8cd98f00b204e9800998ecf8427e-0\"",
            "Size": 0,
            "StorageClass": "STANDARD",
            "Owner": {
                "ID": "1f6"
            }
        }
    ]
}
```

I wonder wether this is good enough with NextCloud or not.

**Comment by kmlebedev** [comment]
Strange HEAD request broke

```
s3_1         | I0815 06:01:58.387118 s3api_object_handlers.go:49 PutObjectHandler test /fakedir/
s3_1         | I0815 06:01:58.387189 filer_client.go:235 mkdir: directory:"/buckets"  entry:{name:"test/fakedir"  is_directory:true  attributes:{mtime:1660543318  file_mode:2147484159  crtime:1660543318  mime:"httpd/unix-directory"}}
s3_1         | I0815 06:01:58.387797 filer_grpc_server.go:139 CreateEntry /buckets/test/fakedir
s3_1         | I0815 06:01:58.387886 filer.go:222 find uncached directory: /buckets/test
s3_1         | I0815 06:01:58.387918 filer.go:186 InsertEntry /buckets/test/fakedir: new entry: fakedir
s3_1         | I0815 06:01:58.388784 filer.go:207 CreateEntry /buckets/test/fakedir: created
s3_1         | I0815 06:01:58.389422 error_handler.go:85 status 200 :
s3_1         | I0815 06:01:58.392909 s3api_object_handlers.go:157 HeadObjectHandler test /fakedir
s3_1         | I0815 06:01:58.393016 s3api_object_handlers.go:319 s3 proxying HEAD to http://172.18.0.4:8888/buckets/test/fakedir
s3_1         | I0815 06:01:58.394094 filer_server_handlers_read_dir.go:55 listDirectory /buckets/test/fakedir, last file , limit 100: 0 items
s3_1         | I0815 06:01:58.395833 error_handler.go:85 status 404 application/xml: <?xml version="1.0" encoding="UTF-8"?>
s3_1         | <Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Resource>/test/fakedir</Resource><RequestId>1660543318395785562</RequestId><Key>fakedir</Key><BucketName>test</BucketName></Error>
s3_1         | I0815 06:01:58.398050 s3api_objects_list_handlers.go:42 ListObjectsV2Handler test
s3_1         | I0815 06:01:58.398789 filer_grpc_server.go:40 ListEntries directory:"/buckets/test/fakedir"  limit:3
s3_1         | I0815 06:01:58.399122 filer_client.go:168 exists entry /buckets/test: directory:"/buckets"  name:"test"
s3_1         | I0815 06:01:58.399832 filer_grpc_server.go:22 LookupDirectoryEntry /buckets/test
s3_1         | I0815 06:01:58.400524 error_handler.go:85 status 200 application/xml: <?xml version="1.0" encoding="UTF-8"?>
s3_1         | <ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Name>test</Name><Prefix>fakedir/</Prefix><MaxKeys>1</MaxKeys><IsTruncated>false</IsTruncated><KeyCount>0</KeyCount></ListBucketResult>
s3_1         | I0815 06:01:58.402992 s3api_object_handlers.go:157 HeadObjectHandler test /fakedir/
s3_1         | I0815 06:01:58.403042 s3api_obje
```

**Comment by kmlebedev** [comment]
Steel need
```
aws --endpoint-url http://127.0.0.1:8333 s3api put-object --content-type "httpd/unix-directory" --bucket test --key "patentdir/fakedir14/"
aws --endpoint-url http://127.0.0.1:8333 s3api list-objects-v2 --bucket test --prefix "parentdir/fakedir14/"
```

**Comment by chrislusf** [comment]
Does NextCloud need it?

**Comment by kmlebedev** [comment]
> Does NextCloud need it?

Yes

**Comment by kmlebedev** [comment]
Снимок экрана 2022-08-15 100320

```
s3_1         | I0815 07:02:56.969739 s3api_object_handlers.go:49 PutObjectHandler test /fakedirnew/
s3_1         | I0815 07:02:56.969896 filer_client.go:235 mkdir: directory:"/buckets"  entry:{name:"test/fakedirnew"  is_directory:true  attributes:{mtime:1660546976  file_mode:2147484159  crtime:1660546976  mime:"httpd/unix-directory"}}
s3_1         | I0815 07:02:56.970547 filer_grpc_server.go:139 CreateEntry /buckets/test/fakedirnew
s3_1         | I0815 07:02:56.970774 filer.go:222 find uncached directory: /buckets/test
s3_1         | I0815 07:02:56.970875 filer.go:186 InsertEntry /buckets/test/fakedirnew: new entry: fakedirnew
s3_1         | I0815 07:02:56.971229 filer.go:207 CreateEntry /buckets/test/fakedirnew: created
s3_1         | I0815 07:02:56.971901 error_handler.go:85 status 200 :
s3_1         | I0815 07:02:56.974378 s3api_object_handlers.go:157 HeadObjectHandler test /fakedirnew
s3_1         | I0815 07:02:56.974468 s3api_object_handlers.go:319 s3 proxying HEAD to http://172.18.0.4:8888/buckets/test/fakedirnew
s3_1         | I0815 07:02:56.974868 filer_server_handlers_read_dir.go:55 listDirectory /buckets/test/fakedirnew, last file , limit 100: 0 items
s3_1         | I0815 07:02:56.975221 error_handler.go:85 status 404 application/xml: <?xml version="1.0" encoding="UTF-8"?>
s3_1         | <Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Resource>/test/fakedirnew</Resource><RequestId>1660546976975169394</RequestId><Key>fakedirnew</Key><BucketName>test</BucketName></Error>
s3_1         | I0815 07:02:56.977586 s3api_objects_list_handlers.go:42 ListObjectsV2Handler test
s3_1         | I0815 07:02:56.978446 filer_grpc_server.go:40 ListEntries directory:"/buckets/test/fakedirnew"  limit:3
s3_1         | I0815 07:02:56.978848 filer_client.go:168 exists entry /buckets/test: directory:"/buckets"  name:"test"
s3_1         | I0815 07:02:56.979292 filer_grpc_server.go:22 LookupDirectoryEntry /buckets/test
s3_1         | I0815 07:02:56.979847 error_handler.go:85 status 200 application/xml: <?xml version="1.0" encoding="UTF-8"?>
s3_1         | <ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Name>test</Name><Prefix>fakedirnew/</Prefix><MaxKeys>1</MaxKeys><IsTruncated>false</IsTruncated><KeyCount>0</KeyCount></ListBucketResult>
s3_1         | I0815 07:02:56.982290 s3api_object_handlers.go:157 HeadObjectHandler test /fakedirnew/
s3_1         | I0815 07:02:56.982353 s3api_object_handlers.go:319 s3 proxying HEAD to http://172.18.0.4:8888/buckets/test/fakedirnew/
s3_1         | I0815 07:02:56.982645 filer_server_handlers_read_dir.go:55 listDirectory /buckets/test/fakedirnew, last file , limit 100: 0 items
s3_1         | I0815 07:02:56.983115 error_handler.go:85 status 404 application/xml: <?xml version="1.0" encoding="UTF-8"?>
s3_1         | <Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Resource>/test/fakedirnew/</Resource><RequestId>1660546976983019176</RequestId><Key>fakedirnew/</Key><BucketName>test</BucketName></Error>
s3_1         | I0815 07:02:57.006304 s3api_objects_list_handlers.go:42 ListObjectsV2Handler test
s3_1         | I0815 07:02:57.007040 filer_grpc_server.go:40 ListEntries directory:"/buckets/test"  limit:10002
s3_1         | I0815 07:02:57.007810 error_handler.go:85 status 200 application/xml: <?xml version="1.0" encoding="UTF-8"?>
s3_1         | <ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Name>test</Name><Prefix></Prefix><MaxKeys>10000</MaxKeys><Delimiter>/</Delimiter><IsTrunca
ted>false</IsTruncated><Contents><Key>Readme.md</Key><ETag>&#34;7215ee9c7d9dc229d2921a40e899ec5f&#34;</ETag><Size>1</Size><Owner><ID>0</ID></Owner><StorageClass>STANDARD</S
torageClass><LastModified>2022-08-15T06:20:32Z</LastModified></Contents><CommonPrefixes><Prefix>fakedir/</Prefix></CommonPrefixes><CommonPrefixes><Prefix>fakedirnew/</Prefi
x></CommonPrefixes><CommonPrefixes><Prefix>lol/</Prefix></CommonPrefixes><CommonPrefixes><Prefix>patentdir/</Prefix></CommonPrefixes><KeyCount>5</KeyCount></ListBucketResult>
nextcloud_1  | 172.18.0.1 - - [15/Aug/2022:07:02:56 +0000] "MKCOL /remote.php/dav/files/admin/s3/fakedirnew HTTP/1.1" 201 603 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36"
nextcloud_1  | 172.18.0.1 - - [15/Aug/2022:07:02:57 +0000] "POST /apps/text/session/sync HTTP/1.1" 200 1036 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36"
s3_1         | I0815 07:02:57.103546 s3api_bucket_handlers.go:199 HeadBucketHandler test
s3_1         | I0815 07:02:57.103960 filer_grpc_server.go:22 LookupDirectoryEntry /buckets/test
s3_1         | I0815 07:02:57.104567 error_handler.go:85 status 200 :
s3_1         | I0815 07:02:57.106909 s3api_objects_list_handlers.go:42 ListObjectsV2Handler test
s3_1         | I0815 07:02:57.107251 filer_grpc_server.go:40 ListEntries directory:"/buckets/test"  limit:10002
s3_1         | I0815 07:02:57.108030 error_handler.go:85 status 200 application/xml: <?xml version="1.0" encoding="UTF-8"?>
s3_1         | <ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Name>test</Name><Prefix></Prefix><MaxKeys>10000</MaxKeys><Delimiter>/</Delimiter><IsTrunca
ted>false</IsTruncated><Contents><Key>Readme.md</Key><ETag>&#34;7215ee9c7d9dc229d2921a40e899ec5f&#34;</ETag><Size>1</Size><Owner><ID>0</ID></Owner><StorageClass>STANDARD</S
torageClass><LastModified>2022-08-15T06:20:32Z</LastModified></Contents><CommonPrefixes><Prefix>fakedir/</Prefix></CommonPrefixes><CommonPrefixes><Prefix>fakedirnew/</Prefi
x></CommonPrefixes><CommonPrefixes><Prefix>lol/</Prefix></CommonPrefixes><CommonPrefixes><Prefix>patentdir/</Prefix></CommonPrefixes><KeyCount>5</KeyCount></ListBucketResult>
s3_1         | I0815 07:02:57.119797 s3api_object_handlers.go:157 HeadObjectHandler test /fakedirnew
s3_1         | I0815 07:02:57.119867 s3api_object_handlers.go:319 s3 proxying HEAD to http://172.18.0.4:8888/buckets/test/fakedirnew
s3_1         | I0815 07:02:57.120240 filer_server_handlers_read_dir.go:55 listDirectory /buckets/test/fakedirnew, last file , limit 100: 0 items
s3_1         | I0815 07:02:57.120519 error_handler.go:85 status 404 application/xml: <?xml version="1.0" encoding="UTF-8"?>
s3_1         | <Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Resource>/test/fakedirnew</Resource><RequestId>1660546977120488736</RequestId><Key>fakedirnew</Key><BucketName>test</BucketName></Error>
s3_1         | I0815 07:02:57.123612 s3api_objects_list_handlers.go:42 ListObjectsV2Handler test
s3_1         | I0815 07:02:57.124056 filer_grpc_server.go:40 ListEntries directory:"/buckets/test/fakedirnew"  limit:3
s3_1         | I0815 07:02:57.124507 filer_client.go:168 exists entry /buckets/test: directory:"/buckets"  name:"test"
s3_1         | I0815 07:02:57.125052 filer_grpc_server.go:22 LookupDirectoryEntry /buckets/test
s3_1         | I0815 07:02:57.125540 error_handler.go:85 status 200 application/xml: <?xml version="1.0" encoding="UTF-8"?>
s3_1         | <ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Name>test</Name><Prefix>fakedirnew/</Prefix><MaxKeys>1</MaxKeys><IsTruncated>false</IsTruncated><KeyCount>0</KeyCount></ListBucketResult>
s3_1         | I0815 07:02:57.127615 s3api_object_handlers.go:157 HeadObjectHandler test /fakedirnew/
s3_1         | I0815 07:02:57.127667 s3api_object_handlers.go:319 s3 proxying HEAD to http://172.18.0.4:8888/buckets/test/fakedirnew/
s3_1         | I0815 07:02:57.127869 filer_server_handlers_read_dir.go:55 listDirectory /buckets/test/fakedirnew, last file , limit 100: 0 items
s3_1         | I0815 07:02:57.128354 error_handler.go:85 status 404 application/xml: <?xml version="1.0" encoding="UTF-8"?>
s3_1         | <Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Resource>/test/fakedirnew/</Resource><RequestId>1660546977128156579</RequestId><Key>fakedirnew/</Key><BucketName>test</BucketName></Error>

```

**Comment by kmlebedev** [comment]
fake dir show 
```
aws --endpoint-url http://127.0.0.1:8333/ s3api list-objects-v2 --bucket test --prefix "fakedirnew" --page-size 1 
{
    "Contents": [
        {
            "Key": "fakedirnew/",
            "LastModified": "2022-08-15T07:02:56Z",
            "ETag": "\"d41d8cd98f00b204e9800998ecf8427e-0\"",
            "Size": 0,
            "StorageClass": "STANDARD",
            "Owner": {
                "ID": "0"
            }
        }
    ]
}
```
fake dir not show
```
 aws --endpoint-url http://127.0.0.1:8333/ s3api list-objects-v2 --bucket test --prefix "fakedirnew/" --page-size 1
```

**Comment by kmlebedev** [comment]
Seems like a HEAD request is optional

**Comment by chrislusf** [comment]
I will leave the NextCloud issue as a regression, since other common cases are more wide spread.

**Comment by kmlebedev** [comment]
> I will leave the NextCloud issue as a regression, since other common cases are more wide spread.

ok

**Comment by kmlebedev** [comment]
> fake dir show
> 
> ```
> aws --endpoint-url http://127.0.0.1:8333/ s3api list-objects-v2 --bucket test --prefix "fakedirnew" --page-size 1 
> {
>     "Contents": [
>         {
>             "Key": "fakedirnew/",
>             "LastModified": "2022-08-15T07:02:56Z",
>             "ETag": "\"d41d8cd98f00b204e9800998ecf8427e-0\"",
>             "Size": 0,
>             "StorageClass": "STANDARD",
>             "Owner": {
>                 "ID": "0"
>             }
>         }
>     ]
> }
> ```
> 
> fake dir not show
> 
> ```
>  aws --endpoint-url http://127.0.0.1:8333/ s3api list-objects-v2 --bucket test --prefix "fakedirnew/" --page-size 1
> ```

https://github.com/seaweedfs/seaweedfs/issues/3738

**Pull request merged**
