### PR TITLE
feat: add col/mark master api to mark collection writable/readonly

### PR DESCRIPTION
**Pull request by zouyixiong**
# What problem are we solving?

A new master api `col/mark?collection=***&flag=writable|readonly` to support collection live control out of the service.

In my usage, I create collection daily, and write to it,  after the day, the collection can be mark as readonly.

(volume server config with max = 0)
I found that, the max available volumes will the affect by the existed writable but not full volumes. So, it's helpful for calc a more correct newMaxVolumeCount if I mark some out of day collection as readonly.

image

# How are we solving the problem?

a new api

# How is the PR tested?
tested in my dev env.

# Checks
- [x] I have added unit tests if possible.
- [x] I will add related wiki document changes and link to this PR after merging.

### CODE REVIEW

**Comment by chrislusf** [comment]
In general, no more http APIs. Only add gRPC APIs.

**Comment by zouyixiong** [comment]
OK, I will change it later.

**Comment by zouyixiong** [comment]
@chrislusf  Updated to grpc api, please check it again.

add a small test here: test/grpc/master/master-grpc-client.go

**Comment by chrislusf** [comment]
* there is already `VolumeMarkReadonly` API

**Pull request closed without merging**
