### PR TITLE
fix helm install error for No such file or directory

### PR DESCRIPTION
**Pull request by cuisongliu**
# What problem are we solving?

#5249 

# How are we solving the problem?

# How is the PR tested?

# Checks
- [ ] I have added unit tests if possible.
- [ ] I will add related wiki document changes and link to this PR after merging.

### CODE REVIEW

**Comment by chrislusf** [comment]
please help to fix some lint errors

**Comment by chrislusf** [comment]
there are a few minor ones from previous PRs:
```
k8s/charts/seaweedfs/values.yaml
  Error: 100:1 [trailing-spaces] trailing spaces
  Error: 259:4 [indentation] wrong indentation: expected 4 but found 3
  Error: 262:19 [trailing-spaces] trailing spaces
  Error: 264:5 [comments] missing starting space in comment
  Error: 313:1 [trailing-spaces] trailing spaces
  Error: 467:1 [trailing-spaces] trailing spaces
  Error: 660:1 [trailing-spaces] trailing spaces
```

**Comment by cuisongliu** [comment]
> there are a few minor ones from previous PRs:
> 
> ```
> k8s/charts/seaweedfs/values.yaml
>   Error: 100:1 [trailing-spaces] trailing spaces
>   Error: 259:4 [indentation] wrong indentation: expected 4 but found 3
>   Error: 262:19 [trailing-spaces] trailing spaces
>   Error: 264:5 [comments] missing starting space in comment
>   Error: 313:1 [trailing-spaces] trailing spaces
>   Error: 467:1 [trailing-spaces] trailing spaces
>   Error: 660:1 [trailing-spaces] trailing spaces
> ```

en ? I not change  k8s/charts/seaweedfs/values.yaml this file .

**Comment by chrislusf** [comment]
thanks! there is one left:
```
k8s/charts/seaweedfs/values.yaml
  Error: missing starting space in comment
```

**Comment by cuisongliu** [comment]
> thanks! there is one left:
> 
> ```
> k8s/charts/seaweedfs/values.yaml
>   Error: missing starting space in comment
> ```

done

**Pull request merged**
