### PR TITLE
revert to avoid potential deadlock

### LINKED ISSUE #4522: Strange behaviour / deadlock with seaweedfs 3.51
Every day we have task with huge amount of writes to seaweedfs cluster. Two days ago we upgraded to 3.51 and since them we've experienced troubles with write. Seaweedfs fuse hangs on writes after some time. This happend two times. Restarting seaweedfs itself helped. For now we've reverted to 3.50 and we experiance no problems again.

I'm writing load test to investigate this problem and will add more info very soon.

### PR DESCRIPTION
**Pull request by wusongANKANG**
# What problem are we solving?

fix  #4522 

# How are we solving the problem?
fallback version (delete code that may introduce deadlock)

# How is the PR tested?

# Checks
- [ ] I have added unit tests if possible.
- [ ] I will add related wiki document changes and link to this PR after merging.

### CODE REVIEW

**Comment by chrislusf** [comment]
seems not needed any more after https://github.com/seaweedfs/seaweedfs/pull/4548

**Comment by wusongANKANG** [comment]
@chrislusf  This pr is to roll back the code introduced by #4491, because #4491 may introduce a new deadlock (deadlock also appeared in our test environment).

#4548 is a new solution to fix the problem: no more writables volumes while disk free space is sufficient 
And #4491 does not completely solve this problem and may cause deadlock. So the solution of #4491 should be deprecated, it needs to be reverted

**Comment by chrislusf** [comment]
Direct reverting has some conflicts. Please send a PR to revert it.

**Comment by wusongANKANG** [comment]
@chrislusf  done in #4550

**Pull request closed without merging**
