### PR TITLE
fix(filer): unescape on delete

### PR DESCRIPTION
**Pull request by mdenushev**
# What problem are we solving?

Deleting/renaming files with spaces in name using S3 doesn't work after 3.66. Caused by adding url escaping on S3 side.

# How are we solving the problem?

Unescape in filer hander

# How is the PR tested?

# Checks
- [x] I have added unit tests if possible.
- [ ] I will add related wiki document changes and link to this PR after merging.

### CODE REVIEW

**Comment by chrislusf** [comment]
Thanks! Will this PR enable some s3 tests currently disabled?

**Comment by kmlebedev** [comment]
@chrislusf Let's get this PR out of the way first?  https://github.com/seaweedfs/seaweedfs/pull/5718

**Comment by kmlebedev** [comment]
@mdenushev  Why can't you separate url escaping logic in s3 from the filler?

**Comment by kmlebedev** [comment]
@mdenushev In my understanding, the filer should not know anything about the encoding. Since this is only on the s3 side. Accordingly, I would like to solve the problem only on the s3 side

**Comment by chrislusf** [comment]
Does this fix a S3 test? If no existing test, needs to add one.

**Comment by kmlebedev** [comment]
> Does this fix a S3 test? If no existing test, needs to add one.

@chrislusf  This is an incorrect fix, since you need to [commit](https://github.com/seaweedfs/seaweedfs/commit/e6bfd061c71ef7ef06e559a6d1d041b997ea633f) to fix it

**Pull request closed without merging**
