### PR TITLE
add pprof for master

### PR DESCRIPTION
**Pull request by dsd2077**
# What problem are we solving?
In some situation, we need pprof to monitor the status of master server. So I add pprof for master.

# How are we solving the problem?
Add a http sock for pprof.

# How is the PR tested?

# Checks
- [ ] I have added unit tests if possible.
- [ ] I will add related wiki document changes and link to this PR after merging.

### CODE REVIEW

**Comment by kungf** [comment]
weed/command/imports.go has import pprof, if you set -metricsPort when start master, you can get the pprof

**Comment by chrislusf** [comment]
does this work with `weed server` also?

**Comment by dsd2077** [comment]
> weed/command/imports.go has import pprof, if you set -metricsPort when start master, you can get the pprof

Thanks for your reply. I have a question "the help manual said metricsPort parameter is for Prometheus. How can I obtain the pprof file?"

**Comment by kungf** [comment]
> > weed/command/imports.go has import pprof, if you set -metricsPort when start master, you can get the pprof
> 
> Thanks for your reply. I have a question "the help manual said metricsPort parameter is for Prometheus. How can I obtain the pprof file?"

curl http://{masterIp}:{metricsPort}/debug/pprof

**Comment by kungf** [comment]
> does this work with `weed server` also?

yes, I tested

**Comment by dsd2077** [comment]
> does this work with `weed server` also?

No. Because ```weed server``` already has it. So does ```weed filer``` and ```weed volume```.

**Comment by dsd2077** [comment]
> > does this work with `weed server` also?
> 
> yes, I tested

I see. Thank you so much.

**Pull request closed without merging**
