### PR TITLE
put v in front of appVersion that is used as image tag

### PR DESCRIPTION
**Pull request by cr1cr1**

### CODE REVIEW

**Comment by chrislusf** [comment]
Does it work with and without "v"?

**Comment by cr1cr1** [comment]
No, hence the reason for the PR. Seems that, starting with `3.33`, the tags include `v`, so `chrislusf/seaweedfs:3.33` does not work but `chrislusf/seaweedfs:v3.33`

**Comment by cr1cr1** [comment]
Before PR:
```
2m19s       Normal    BackOff  pod/seaweedfs-volume-2  Back-off pulling image "chrislusf/seaweedfs:3.33"
```

after:
```
115s        Normal    Pulling  pod/seaweedfs-volume-2  Pulling image "chrislusf/seaweedfs:v3.33"
110s        Normal    Pulled  pod/seaweedfs-volume-2  Successfully pulled image "chrislusf/seaweedfs:v3.33" in 5.550181397s
```

**Comment by chrislusf** [comment]
this is due to a release error. I created a `3.33` release just now to replace `v3.33`.

**Pull request merged**
