### PR TITLE
Add disk type to prometheus metrics

### PR DESCRIPTION
**Pull request by dimm0**
# What problem are we solving?
Add the type of disk to prometheus

# How are we solving the problem?
Adding the corresponding label

# How is the PR tested?
Not tested

# Checks
- [ ] I have added unit tests if possible.
- [ ] I will add related wiki document changes and link to this PR after merging.

### CODE REVIEW

**Comment by chrislusf** [comment]
Sorry I accidentally merged this PR, not sure whether this PR was ready or not.

**Comment by dimm0** [comment]
It was ready on the part I needed, but you wanted more code for parts I don't use and which are harder to implement

**Comment by dimm0** [comment]
@chrislusf so can we make this happen?

**Comment by chrislusf** [comment]
merged back in the master

**Comment by chrislusf** [comment]
Sorry. Need to revert due to several test failures.

**Comment by dimm0** [comment]
I'm querying the json from master directly, but that doesn't have types either.. Is it easier to add the types to it?

**Comment by chrislusf** [comment]
disk type is already in `/vol/status`. Default empty string means it is `hdd`.

```
 curl http://localhost:9333/vol/status | jq .
{
  "Version": "30GB 3.57 ",
  "Volumes": {
    "DataCenters": {
      "DefaultDataCenter": {
        "DefaultRack": {
          "192.168.2.7:8085": [
            {
              "Id": 3,
              "Size": 1577094440,
              "ReplicaPlacement": {},
              "Ttl": {
                "Count": 0,
                "Unit": 0
              },
              "DiskType": "",
              "Collection": "",
              "Version": 3,
              "FileCount": 753,
              "DeleteCount": 1,
              "DeletedByteCount": 2097171,
              "ReadOnly": false,
              "CompactRevision": 0,
              "ModifiedAtSecond": 1695442649,
              "RemoteStorageName": "",
              "RemoteStorageKey": ""
            },
```

**Comment by kmlebedev** [comment]
Please fix it:
```
I1013 11:02:58.926250 needle_map_memory.go:54 max file key: 3060820472027866331 for file: /Users/lebedev/sw/disk2/default_5774.idx
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x38 pc=0x1017f962c]

goroutine 74 [running]:
github.com/seaweedfs/seaweedfs/weed/storage.(*Volume).DiskType(...)
        /Users/lebedev/GolandProjects/seaweedfs/weed/storage/volume.go:205
github.com/seaweedfs/seaweedfs/weed/storage.(*Volume).load(0x14000918000, 0x1, 0x1, 0x0, 0x11?)
        /Users/lebedev/GolandProjects/seaweedfs/weed/storage/volume_loading.go:204 +0x14bc
github.com/seaweedfs/seaweedfs/weed/storage.NewVolume({0x16fb9f89a, 0x17}, {0x16fb9f89a, 0x17}, {0x140005b40a8, 0xc}, 0x168e, 0x0, 0x0, 0x0, ...)
        /Users/lebedev/GolandProjects/seaweedfs/weed/storage/volume.go:64 +0x198
github.com/seaweedfs/seaweedfs/weed/storage.(*DiskLocation).loadExistingVolume(0x140008b0cc0, {0x1035be348, 0x140009881c0}, 0x1400050b701?, 0x1, 0x1035be640?)
        /Users/lebedev/GolandProjects/seaweedfs/weed/storage/disk_location.go:173 +0x31c
github.com/seaweedfs/seaweedfs/weed/storage.(*DiskLocation).concurrentLoadingVolumes.func2()
        /Users/lebedev/GolandProjects/seaweedfs/weed/storage/disk_location.go:213 +0x94
created by github.com/seaweedfs/seaweedfs/weed/storage.(*DiskLocation).concurrentLoadingVolumes in goroutine 72
        /Users/lebedev/GolandProjects/seaweedfs/weed/storage/disk_location.go:210 +0xcc
```

**Pull request merged**
