### PR TITLE
Create command_volume_recycle.go

### PR DESCRIPTION
**Pull request by fc-coder**
Recycle files according to cluster usage

### CODE REVIEW

**Comment by chrislusf** [comment]
1. Go fmt.
2. Should require locking, similar to https://github.com/chrislusf/seaweedfs/blob/master/weed/shell/command_volume_balance.go#L65

**Comment by LazyDBA247-Anyvision** [comment]
@fc-coder any update? sound interesting...

**Comment by kmlebedev** [comment]
> @fc-coder any update? sound interesting...

I don't understand what is the use?

**Comment by kmlebedev** [comment]
@fc-coder ping

**Comment by kmlebedev** [comment]
While the refactoring realized that this is a useless command, it tries to delete the tail of volumes of data files when the disk is full

**Pull request closed without merging**
