### PR TITLE
[master] fix master panic

### PR DESCRIPTION
**Pull request by wusongANKANG**
# What problem are we solving?

master panic: fatal error: concurrent map iteration and map write
image

# How are we solving the problem?

# How is the PR tested?

# Checks
- [ ] I have added unit tests if possible.
- [ ] I will add related wiki document changes and link to this PR after merging.

### CODE REVIEW

**Comment by chrislusf** [comment]
How about refactor the code to use the lock only inside disk.go file?

**Comment by wusongANKANG** [comment]
> How about refactor the code to use the lock only inside disk.go file?

done

**Comment by winwill2012** [comment]
Is the following issue also related？
image
Reproduction Steps： 
1. start weed shell process
2. run `weed move`
3. move and tail operator has already completed, but source volume server rpc occur exception while deleting source volume

thanks~

**Comment by wusongANKANG** [comment]
@winwill2012  This issue doesn't seem to be related to your problem. This is master panic, while yours is volume panic.

Which version are you using?

**Pull request merged**
