### PR TITLE
[filer]fix: limit the directory move to non-empty directory and file

### PR DESCRIPTION
**Pull request by wusongANKANG**
# What problem are we solving?
limit the directory move to non-empty directories and files.

refer to #4045 

# How are we solving the problem?
refer to StreamRenameEntry function

# How is the PR tested?

# Checks
- [ ] I have added unit tests if possible.
- [ ] I will add related wiki document changes and link to this PR after merging.

### CODE REVIEW

**Comment by chrislusf** [comment]
why is this needed?

**Comment by wusongANKANG** [comment]
In order to maintain the same behavior as mount.
Or is it by design that this restriction is not needed?

**Comment by chrislusf** [comment]
Could you please show the related code in mount?

**Comment by wusongANKANG** [comment]
Maybe it wasn't clear.
 After the mount executes the rename operation, the filer side uses the StreamRenameEntry function for processing. This restriction is done in the StreamRenameEntry function.

The AtomicRenameEntry function handles http rename, so I also added this restriction to AtomicRenameEntry.

**Comment by chrislusf** [comment]
there should not be this limitation. Moving a directory to an non-empty directory should be fine.

**Pull request closed without merging**
