### PR TITLE
avoid grpc protocol service critical change

### PR DESCRIPTION
**Pull request by kmlebedev**
# What problem are we solving?

fix conflicts 
https://github.com/seaweedfs/seaweedfs/pull/3680

# How are we solving the problem?

# How is the PR tested?

# Checks
- [ ] I have added unit tests if possible.
- [ ] I will add related wiki document changes and link to this PR after merging.

### CODE REVIEW

**Comment by chrislusf** [comment]
this is not needed now?

**Comment by kmlebedev** [comment]
> this is not needed now?

@chrislusf Need now. Please read this https://developers.google.com/protocol-buffers/docs/proto3#updating

> Don't change the field numbers for any existing fields.

**Comment by chrislusf** [comment]
The diff is only moving the proto definition to the end of the file.

**Comment by kmlebedev** [comment]
> The diff is only moving the proto definition to the end of the file.

Yes.

**Comment by chrislusf** [comment]
The ordering in the proto file should not matter.

**Pull request closed without merging**
