### PR TITLE
shell meta load add concurrency

### PR DESCRIPTION
**Pull request by kmlebedev**
# What problem are we solving?

# How are we solving the problem?

# How is the PR tested?

# Checks
- [ ] I have added unit tests if possible.
- [ ] I will add related wiki document changes and link to this PR after merging.

### CODE REVIEW

**Comment by chrislusf** [comment]
This can cause problems where file metadata is created first before the directory. To fix this, we can iterate through the folders as a single thread, and then concurrently to process all the files.

**Comment by kmlebedev** [comment]
> This can cause problems where file metadata is created first before the directory. To fix this, we can iterate through meta dump twice: the first time to process the folders as a single thread, and the second time concurrently process all the file metadata.


@chrislusf I'm not sure if this is a problem at the time of loading.
The base scheme allows you to load in any order, and the display may suffer at the moment, but this is expected
```
create table seaweedfs.filemeta
(
    dirhash   bigint        not null comment 'first 64 bits of MD5 hash value of directory field',
    name      varchar(1000) not null comment 'directory or file name',
    directory text          null comment 'full path to parent directory',
    meta      longblob      null,
    primary key (dirhash, name)
)
    charset = utf8;
```

**Comment by chrislusf** [comment]
for example, this would not work well for Redis.

**Comment by kmlebedev** [comment]
@chrislusf I left one pass before creating folders in one thread, since only folders always go at the beginning of the file.

**Pull request merged**
