### PR TITLE
fix:mount deadlock

### PR DESCRIPTION
**Pull request by zemul**
# What problem are we solving?
#4346 

# How are we solving the problem?

# How is the PR tested?

# Checks
- [ ] I have added unit tests if possible.
- [ ] I will add related wiki document changes and link to this PR after merging.

### CODE REVIEW

**Comment by neo-v** [comment]
how about erase fh.entryLock.Lock()

**Comment by zemul** [comment]
> how about erase fh.entryLock.Lock()
no problem.

**Comment by zemul** [comment]
@chrislusf

**Comment by chrislusf** [comment]
Is this still needed? If so, please write down some pseudo code describing current relationships between the two locks, to show why this PR can help and why it won't cause problems.

**Pull request closed without merging**
