### PR TITLE
feat: add support for S3 ListObjects and ListObjectsV2

### PR DESCRIPTION
**Pull request by adasauce**
# What problem are we solving?

Object list delimiters currently raise a `ErrNotImplemented`

Issue #4853 

# How are we solving the problem?

By grouping similar objects under the `CommonPrefixes` if a `Delimiter` is supplied by the request.

See docs here for implementation details:

https://docs.aws.amazon.com/AmazonS3/latest/API/API_ListObjectsV2.html#API_ListObjectsV2_ResponseSyntax

# How is the PR tested?

Using `ceph/s3-tests` and based on the Dockerfile in tests/s3/compatibility.

```bash
docker run --name s3tests-seaweedfs \
  --rm --net=host \
  -e S3TEST_CONF=s3tests.conf \
  -v ./s3tests.conf:/s3-tests/s3tests.conf \
  -v ./tox:/s3-tests/.tox \
  -it s3tests \
  tox -- -v -W ignore::DeprecationWarning ./s3tests_boto3/functional/test_s3.py -k "test_bucket_listv2_delimiter and not (test_bucket_listv2_delimiter_basic or test_bucket_listv2_delimiter_prefix or test_bucket_listv2_delimiter_prefix_underscore)"

.pkg: _optional_hooks> python /usr/local/lib/python3.11/site-packages/pyproject_api/_backend.py True setuptools.build_meta __legacy__
.pkg: get_requires_for_build_sdist> python /usr/local/lib/python3.11/site-packages/pyproject_api/_backend.py True setuptools.build_meta __legacy__
.pkg: get_requires_for_build_wheel> python /usr/local/lib/python3.11/site-packages/pyproject_api/_backend.py True setuptools.build_meta __legacy__
.pkg: prepare_metadata_for_build_wheel> python /usr/local/lib/python3.11/site-packages/pyproject_api/_backend.py True setuptools.build_meta __legacy__
.pkg: build_sdist> python /usr/local/lib/python3.11/site-packages/pyproject_api/_backend.py True setuptools.build_meta __legacy__
py: install_package> python -I -m pip install --force-reinstall --no-deps /s3-tests/.tox/.tmp/package/32/s3tests-0.0.1.tar.gz
py: commands[0]> pytest -v -W ignore::DeprecationWarning ./s3tests_boto3/functional/test_s3.py -k 'test_bucket_listv2_delimiter and not (test_bucket_listv2_delimiter_basic or test_bucket_listv2_delimiter_prefix or test_bucket_listv2_delimiter_prefix_underscore)'
========================================================================================================= test session starts =========================================================================================================
platform linux -- Python 3.11.8, pytest-8.0.2, pluggy-1.4.0 -- /s3-tests/.tox/py/bin/python
cachedir: .tox/py/.pytest_cache
rootdir: /s3-tests
configfile: pytest.ini
collected 545 items / 537 deselected / 8 selected                                                                                                                                                                                     

s3tests_boto3/functional/test_s3.py::test_bucket_listv2_delimiter_alt PASSED                                                                                                                                                    [ 12%]
s3tests_boto3/functional/test_s3.py::test_bucket_listv2_delimiter_percentage PASSED                                                                                                                                             [ 25%]
s3tests_boto3/functional/test_s3.py::test_bucket_listv2_delimiter_whitespace PASSED                                                                                                                                             [ 37%]
s3tests_boto3/functional/test_s3.py::test_bucket_listv2_delimiter_dot PASSED                                                                                                                                                    [ 50%]
s3tests_boto3/functional/test_s3.py::test_bucket_listv2_delimiter_unreadable PASSED                                                                                                                                             [ 62%]
s3tests_boto3/functional/test_s3.py::test_bucket_listv2_delimiter_empty PASSED                                                                                                                                                  [ 75%]
s3tests_boto3/functional/test_s3.py::test_bucket_listv2_delimiter_none PASSED                                                                                                                                                   [ 87%]
s3tests_boto3/functional/test_s3.py::test_bucket_listv2_delimiter_not_exist PASSED                                                                                                                                              [100%]

================================================================================================== 8 passed, 537 deselected in 3.30s ==================================================================================================
.pkg: _exit> python /usr/local/lib/python3.11/site-packages/pyproject_api/_backend.py True setuptools.build_meta __legacy__
  py: OK (4.09=setup[0.65]+cmd[3.44] seconds)
  congratulations :) (4.12 seconds)
``` 

the following tests are still failing, but it's because of some prefix functionality breaking, and they just all use the "/" delimiter, so don't really exercise this PR.

 - test_bucket_listv2_delimiter_basic
 - test_bucket_listv2_delimiter_prefix
 - test_bucket_listv2_delimiter_prefix_underscore

# Checks
- [x] I have added unit tests if possible.
- [ ] I will add related wiki document changes and link to this PR after merging.

### CODE REVIEW

**Comment by kmlebedev** [comment]
@chrislusf It is necessary to roll back or fix the regression tests, the tests that worked in the previous version are broken
```
=========================== short test summary info ============================
FAILED s3tests_boto3/functional/test_s3.py::test_bucket_listv2_delimiter_prefix
FAILED s3tests_boto3/functional/test_s3.py::test_bucket_listv2_delimiter_prefix_underscore
FAILED s3tests_boto3/functional/test_s3.py::test_bucket_list_prefix_delimiter_basic
FAILED s3tests_boto3/functional/test_s3.py::test_bucket_listv2_prefix_delimiter_basic
============ 4 failed, 123 passed, 11 warnings in 135.17s (0:02:15) ============
```

We put a lot of effort into making this test work.
```
__________________ test_bucket_listv2_prefix_delimiter_basic ___________________
    @pytest.mark.list_objects_v2
    def test_bucket_listv2_prefix_delimiter_basic():
        key_names = ['foo/bar', 'foo/baz/xyzzy', 'quux/thud', 'asdf']
        bucket_name = _create_objects(keys=key_names)
        client = get_client()
    
        response = client.list_objects_v2(Bucket=bucket_name, Delimiter='/', Prefix='foo/')
        assert response['Prefix'] == 'foo/'
        assert response['Delimiter'] == '/'
    
        keys = _get_keys(response)
        prefixes = _get_prefixes(response)
>       assert keys == ['foo/bar']
E       AssertionError: assert [] == ['foo/bar']
E         Right contains one more item: 'foo/bar'
E         Use -v to get more diff
s3tests_boto3/functional/test_s3.py:868: AssertionError
--------------------------- Captured stdout teardown ---------------------------
```

**Comment by adasauce** [comment]
I'll have a look into why this test isn't passing ifit was going before. 

I did call out in the PR that the test was failing, but assumed it had done because of prefix code not delimiter code.

**Comment by adasauce** [comment]
Just going through the test + some debugging output now.

```
auth_credentials.go:382 user name: some_admin_user actions: [Admin Read List Tagging Write], action: List
s3api_objects_list_handlers.go:42 ListObjectsV2Handler yournamehere-pbxj6idb0rk8mvc3-1
filer_grpc_server.go:42 ListEntries directory:"/buckets/yournamehere-pbxj6idb0rk8mvc3-1" prefix:"foo" limit:1
filer_grpc_server.go:42 ListEntries directory:"/buckets/yournamehere-pbxj6idb0rk8mvc3-1/foo" limit:10002
s3api_objects_list_handlers.go:172 fullPath: foo/bar, delimitedPath: [foo bar]
s3api_objects_list_handlers.go:175 delimited path found
s3api_objects_list_handlers.go:176 delimitedPath[0]: foo, delimitedPath[1]: bar
s3api_objects_list_handlers.go:180 delimitedPrefix: foo/
s3api_objects_list_handlers.go:196 delimiterFound: true, commonPrefixes: [{foo/}]
filer_client.go:168 exists entry /buckets/yournamehere-pbxj6idb0rk8mvc3-1: directory:"/buckets" name:"yournamehere-pbxj6idb0rk8mvc3-1"
filer_grpc_server.go:24 LookupDirectoryEntry /buckets/yournamehere-pbxj6idb0rk8mvc3-1
error_handler.go:96 status 200 application/xml: <?xml version="1.0" encoding="UTF-8"?>
<ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Name>yournamehere-pbxj6idb0rk8mvc3-1</Name><Prefix>foo/</Prefix><MaxKeys>10000</MaxKeys><Delimiter>/</Delimiter><IsTruncated>false</IsTruncated><CommonPrefixes><Prefix>foo/</Prefix></CommonPrefixes><CommonPrefixes><Prefix>foo/baz/</Prefix></CommonPrefixes><KeyCount>2</KeyCount></ListBucketResult>
```

It's returning foo/ as a commonPrefix because of the "/" delimiter being supplied.

from the example in amazon's docs they say:
```
For example, if the prefix is notes/ and the delimiter is a slash (/) as in notes/summer/july, the common prefix is notes/summer/. All of the keys that roll up into a common prefix count as a single return when calculating the number of returns. 
```

the problem is the new delimeter code wasn't taking into account the prefix to identify whether the path should be included. it's splitting on the first occurrence of / but not after 'foo/' because foo/bar doesn't end in a slash it should'nt be a common prefix.

**Comment by adasauce** [comment]
update: tests passing. running through some other ones that were passing with the original PR to make sure there isn't a regression.

```
collected 545 items / 542 deselected / 3 selected                                                                                                                   

s3tests_boto3/functional/test_s3.py::test_bucket_listv2_delimiter_prefix PASSED                                                                               [ 33%]
s3tests_boto3/functional/test_s3.py::test_bucket_listv2_delimiter_prefix_ends_with_delimiter PASSED                                                           [ 66%]
s3tests_boto3/functional/test_s3.py::test_bucket_listv2_delimiter_prefix_underscore PASSED                                                                    [100%]

```

**Comment by adasauce** [comment]
> If the tests are not fixed, we will lose support for the popular `restic` client Use this list of tests to check [#5237 (comment)](https://github.com/seaweedfs/seaweedfs/pull/5237#issuecomment-1908771738)

```
======================================================================= 125 passed in 39.11s ========================================================================
.pkg: _exit> python /usr/local/lib/python3.11/site-packages/pyproject_api/_backend.py True setuptools.build_meta __legacy__
  py: OK (39.89=setup[0.64]+cmd[39.26] seconds)
  congratulations :) (39.92 seconds)
```

apologies for the regression. pushing the changes up now.

**Pull request merged**
